title: Rodrigo Lorca # your name (or website title) here
logo: "photomid.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have experience developing multiple projects as a Data Scientist,
  leading machine learning to data-driven strategies for multiple companies in Chile and Latam.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/rodrigolorcas/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
